alerts/duo_fail_open.py

Alerts when fDuoSecurity contact fails, which is means either authentication was refused, either granted based on a
single authentication factor ("fail open").
How does that look like? For example, the aggregation is based on one term only since it makes sense to always alert. But I'm not sure if that's the correct way to do that.
Also, I'm not 100% sure about the term and query filter.  I suppose using _source or directly the name works.. but I'm not sure at all :)
I based myself on https://github.com/jeffbryner/MozDef/blob/master/alerts/bruteforce_ssh_pyes.py 
Related bug https://bugzilla.mozilla.org/show_bug.cgi?id=971606

New alert for https://github.com/mozilla-it/duo_openvpn

---

meteor/app/client/globe.js

Fixes three.js deprecated warning for globe visualization 
`DEPRECATED: GeometryUtils's .merge() has been moved to Geometry. Use geometry.merge( geometry2, matrix, materialIndexOffset ) instead.`

Fixed Deprecated warning about `GeometryUtil's .merge()` in globe visualization

---

cron/cloudtrail2mozdef.conf
cron/cloudtrail2mozdef.py

Added the ability to iterate over multiple AWS accounts, multiple regions, and the s3 buckets associated with the CloudTrail in each account/region combination
* Added RoleManager to cache and manage assumed IAM roles and their credentials
* Added HACK to workaround missing permissions requested in https://bugzilla.mozilla.org/show_bug.cgi?id=1216784
* Added State class to manage and store state instead of writing state to the config file
* Constrained s3 bucket key searches to the specific paths that we're interested in, instead of all keys in all paths of the bucket
* Constrained searches for account/region combinations which have no lastrun value to the previous hour instead of the previous 2 days
* Added new options
* aws_accounts : comma delimited list of AWS account IDs to gather …

Added the ability to iterate over multiple AWS accounts, multiple regions

---

mq/plugins/fluentdSqsFixup.py

tested on mozdefqa1, has some test cases included.
defaults to both nubis prod and non-prod messages

Normalizer for fluentd-sqs events

---

mq/plugins/fluentdSqsFixup.py

Removing duplicate field "details.time" via fluentdSqsFixup plugin

Remove details.time from fluentdSqsFixup

---

alerts/geomodel.py

Only create alerts using the geomodel plugin if the severity on the original event meets or exceeds noted severity.

take severity into account in geomodel alert plugin

---

alerts/alertPluginsmules.ini

Had to modify some things with this, the uwsgi- seemed to cause problems with the pid and fifo.
I've modified naming conventions to be more inline with the mq based uwsgi files.
lowercase initial letter, second word capitalized, and mules is lowercase: alertPluginsmules.ini
I also removed the 5 mule processes and enabled-threads instead. Allowing the fifo to control the processes is better than trying to capture the pid of every process that spawns.

Adding updated uwsgi ini config file for mozdefalertplugins init script.

---

cron/cloudtrail2mozdef.py

Remove cloudtrail logic which hard codes the S3 bucket name if the script can not authenticate to the target AWS account.
https://bugzilla.mozilla.org/show_bug.cgi?id=1217976
Reverts portion of f84e9726a703147295ea07c2ac56378ad353c945

Remove cloudtrail logic which hard codes the S3 bucket name

---

docs/source/usage.rst

As this field is not actually used by any event generators, it's not a mandatory field

Removing reference to "source" field

---

alerts/lib/alerttask.py

Fixes the alert logic to ensure that if an IRC channel is specified, the message will be displayed by the bot

Improve logic on which messages will be filtered by the IRC bot

---

.travis.yml

Supports: https://github.com/mozilla/MozDef/issues/406

Add Python 2.7.12 and 2.7.13 to CI coverage

---

docker/compose/mozdef_meteor/Dockerfile

This makes it so if we update settings.js, we don't have to install meteor and all of it's dependencies.

Modify meteor dockerfile to copy settings after dep install

---

lib/query_models/__init__.py
lib/query_models/less_than_match.py
tests/lib/query_models/test_less_than_match.py
tests/lib/query_models/test_range_match.py

This is so we can support alerts that check for events with 'old' timestamps

Add less than match query model

---

meteor/app/client/incidentsveris.js

Currently we are using the default 50 item limit for tags, which we overrun quickly when tagging incidents. The pivot table can handle quite a bit more, this just ups the limit to avoid the dreaded:

fix "too many items" problem in the tags pivot table

---

.travis.yml

This is due to how travis builds their containers, so this fix is only restricted to travis and how we use them to run our unit tests.

Set botoconfig to null for travis builds

---

alerts/old_events.py
tests/alerts/test_old_events.py
tests/unit_test_suite.py

This alert will detect when we have problems in our event pipeline. It detects when an event utctimestamp is set over a day old, but yet, the receivedtimestamp field is recent.

Add alert for old events

---

cron/backupSnapshot.py

This prevents the cron email from reporting even when the script executes as expected.

Modify logger level in backup snapshot cron

---

docker/compose/docker-compose.yml
docker/compose/mozdef_fluentd/Dockerfile
docker/compose/mozdef_fluentd/files/fluent.conf

This will provide a 'syslog server' interface for sending events to mozdef.

Add fluentd container to consume syslog logs

---

systemdfiles/alert/mozdefalertplugins.service
systemdfiles/alert/mozdefalerts.service
systemdfiles/alert/mozdefbot.service
systemdfiles/alert/mozdefloginput.service
systemdfiles/consumer/mozdefloginput.service
systemdfiles/consumer/mozdefmqwsyslog.service
systemdfiles/web/mongod.service
systemdfiles/web/mozdefrestapi.service

This fixes the issue of "ExecStartPre=/usr/bin/mkdir /var/run/mozdef-alerts (code=exited, status=1/FAILURE)" showing up in red text in the output of 'systemctl status <mozdefservicename>'.

Suppress mkdir exit status in systemd files

---

alerts/sshkey.conf
alerts/sshkey.py
tests/alerts/test_sshkey.py

Adds sshkey alert, which can consume event information generated by
mig-runner and MIG's sshkey module.

add sshkey alert

---

alerts/ssh_password_auth_violation.py
tests/alerts/test_ssh_password_auth_violation.py

This adds warning alerts in cases where a public ssh endpoint is detected that allows password auth, which is a no-no.

Add ssh password auth violation alert

---

tests/conftest.py
tests/unit_test_suite.py

This ensures that when you run unit tests, the help text that describes the available py.test flags will always be displayed to the end user. 
An example of this text is https://travis-ci.org/mozilla/MozDef/jobs/281013069#L761

Move unit test flag output to conftest

---

docker/compose/mozdef_meteor/Dockerfile
docker/compose/mozdef_meteor/files/settings.js
meteor/app/client/attackers.js

Variety of fixes for issues I encountered in the 'multiple' docker build. 
Probably the biggest is: For me, it wouldn't even build complaining of an EXDEV error that appears to be fixed in the subsequent version of meteor. So bumped the version. 
Minor but still intriguing is a change to the attacker selection criteria due to the date always being init'd as now() rather than 1970.
The chown -R is removed since it touches thousands of files, takes forever on a rebuild, and isn't really needed if we just chown the dir.

Misc docker fixes

---

docker/Dockerfile
docker/compose/elasticsearch/Dockerfile
docker/compose/kibana/Dockerfile
docker/compose/mongodb/Dockerfile
docker/compose/mozdef_base/Dockerfile
docker/compose/mozdef_meteor/Dockerfile
docker/compose/mozdef_syslog/Dockerfile
docker/compose/nginx/Dockerfile
docker/compose/rabbitmq/Dockerfile

https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

MAINTAINER is deprecated, using LABEL now

---

config/defaultMappingTemplate.json

I found that tags are currently entered as a string, but @pwnbus mentioned them being an array.
There are some items that I didn't add to this defaulttemplate, and figure we can discuss those items at a later date after the holiday. The fields with the most potential of being added as a number or other field type other than string are what have been added here.

Adding mandatory fields to mapping.

---

meteor/public/css/mozdef.css

in relation to the menu bar on screen resizing. Works on 4k.
Previously the logo and name were HUGE on a 4k screen compared to the menu options.
Have tested this on 4k and regular 1080p

Modifying size of the font and image

---

bot/mozdefbot_slack.conf
bot/mozdefbot_slack.py

This is not a complete swap for swap functionality with the IRC bot. It currently doesn't include any ability to respond to commands, but this way, we at least have a rough bot that folks can use to get alerts in slack channels.

Create rough implementation of mozdefbot for slack

---

alerts/geomodel.py
tests/alerts/test_geomodel.py

This fixes the 'locality_details' error we're seeing in the alert error logs. 
This is due to the fact that movement alerts don't have the specific fields that we are about setting in 'details'. Since we aren't sending movement alerts to the SSO dashboard, we can simply ignore setting those fields.

Update geomodel alert to exclude additional attributes logic

---

meteor/app/client/menu.html
meteor/public/css/mozdef.css

Logo size change moved the menu header to the right, no longer centers. This fixes.

Center the header

---

meteor/app/client/incidentTable.html
meteor/app/client/investigationTable.html

As a part of the UI Interviews it was stated it would be nice to see who opened an investigation or incident without having to hover over the entry. 
This adds this functionality.

Adding creator column to investigations and incidents

---

tests/alerts/alert_test_suite.py
tests/requirements_tests.txt

This locks the datetime in alert tests, so that we have more of a controlled environment.

Lock alert tests into specific datetime

---

cron/healthToMongo.py
meteor/app/client/mozdefhealth.html

Old GC times are crucial to a healthy JVM - adding this stat so we can be aware when gc is going over recommended times. This can also alert us to high volume shards which may indicate a need to add additional shards.

Adding old garbage collection stats to About page.

---

lib/elasticsearch_client.py
lib/utilities/is_cef.py
lib/utilities/logger.py
lib/utilities/remove_at.py
lib/utilities/to_unicode.py
mq/esworker_cloudtrail.py
mq/esworker_eventtask.py
mq/esworker_papertrail.py
mq/esworker_sns_sqs.py
mq/esworker_sqs.py
mq/lib/plugins.py
mq/plugins/complianceitems.py
mq/plugins/vulnerability.py

In addition, we remove some unused code/refactor some common functions into lib.
We also print the malformed event to the log for each worker, so that troubleshooting issues will be easier.

Modify workers to use logger

---

cron/auth02mozdef.sh
cron/backupSnapshot.sh
cron/collectAttackers.sh
cron/collectSSHFingerprints.sh
cron/correlateUserMacAddress.sh
cron/createIPBlockList.sh
cron/duo_logpull.sh
cron/duo_logpull_releng.sh
cron/esMaint.sh
cron/eventStats.sh
cron/google2mozdef.sh
cron/healthAndStatus-fxa.sh
cron/healthAndStatus-mdc1.sh
cron/healthAndStatus.sh
cron/healthToMongo.sh
cron/import_threat_exchange.sh
cron/okta2mozdef.sh
cron/pruneES.sh
cron/syncAlertsToMongo.sh
cron/update_generic_alerts.sh
cron/update_geolite_db.sh
cron/update_ip_list.sh
cron/verify_event_fields.sh
cron/vidyo2MozDef.sh

Changed python virtualenv to /opt/mozdef/envs/python in `cron/*.sh` files
FIxes #421

Changed python virtualenv locations in cron/*.sh

---

alerts/bruteforce_ssh.py

Currently we do not see any failed logins that use publickeys, we should be seeing these.
I expect the rate of fire for this alert to increase significantly as we are about to find out where possible script issues are in addition to users attempting to log into hosts where their key is not present.

Add publickey to TermsMatch 

---

meteor/app/client/mozdef.js

What would happen:
- XHR triggers while page is open
- User session has to be verified with an authentication provider by an
access proxy (Meteor is unaware of this)
- XHR gets a 302 reply to the authentication provider, but doesn't know
what to do with it.
- Additionally, CORS headers deny the 302 (rightfully so)
- All XHRs fail from now on, Mozdef webui stops working until you
manually refresh the page.
What happens with this patch:
- XHR triggers while page is open
- User session has to be verified with an authentication provider by an
access proxy (Meteor is unaware of this)
+ XHR reply is intercepted and checks if it's a 302 or 0 (CORS denial)
status
++ if so, the page is automatically refreshed and the user gets silently
reauthenticated as needed

Fix XHR 302s with an access proxy. This fixes the page "hanging" after the access proxy tries to silently authenticate.

---

meteor/app/client/alertdetails.html
meteor/app/client/alertdetails.js
meteor/app/client/alertssummary.html
meteor/app/client/alertsummary.js
meteor/app/client/attackerdetails.html
meteor/app/client/attackerdetails.js
meteor/app/client/ipBlocklistTable.html
meteor/app/client/ipBlocklistTable.js
meteor/app/client/layout.js
meteor/app/client/menu.js
meteor/app/client/mozdef.js
meteor/mozdef.html

This adds a 'copy to clipboard' option for the ip address drop down menu and cleans up the ip drop down modal html/js to be centralized in the layout template rather than duplicated in all the screens that may need it.

Add a "copy to clipboard" option for ip addresses

---

mq/esworker_sns_sqs.py

If the sqs message contains, source, summary or processname use them.

Pull in required fields

---

cron/createFDQNBlockList.py
cron/createFQDNBlockList.conf
cron/createFQDNBlockList.sh
meteor/app/client/blockFDQN.js
meteor/app/client/blockFQDN.html
meteor/app/client/fqdnBlocklistTable.html
meteor/app/client/fqdnBlocklistTable.js
meteor/app/client/menu.html
meteor/app/client/mozdef.js
meteor/app/lib/collections.js
meteor/app/router/router.js
meteor/app/server/methods.js
meteor/mozdef.html
rest/index.py
rest/plugins/fqdnblocklist.conf
rest/plugins/fqdnblocklist.py

I'm not very "webby" in the context of developing web-pages, though I do like to break them.  Here's an attempt at cloning something we've already built for IP/network block lists and porting to work for FQDNs (Fully Qualified Domain Names).  The idea being that if a SPOC needs to respond to say block a phishing domain, they could drop into the UI and take decisive action to "add it to the FQDN blocklist" and that could be consumed by other services (see bug 1454672), like the proxy servers, DNS servers, and maybe even AWS security groups to protect our users and our services from said bad FQDN.
I've also marked this a WIP (Work In Progress) to start with since I'm starting with just modding code, getting some initial review, and I've not actually even tested this to make sure it doesn't …

Add FQDN/DNS block page

---

mq/plugins/cloudtrail.py

Log errors say details.requestparameters.instanceType is sometimes an object:
"instanceType": {"value": "t2.medium"}}

Add details.requestparameters.instanceType

---

config/logrotate-mongod
config/logrotate-mozdef
config/logrotate-nginx

This update to our logrotate scripts moves the archived logs out of the original log directory into an archive directory. I've also added the su directive for those directories rotated from that are owned by mozdef instead of root.

Adding updated logrotate scripts for mozdef archival of old logs.

---

alerts/auditd_sftp.py
alerts/bruteforce_ssh.py
alerts/duo_fail_open.py
alerts/generic_alert_loader.py
alerts/lib/alerttask.py
alerts/promisc_kernel.py
alerts/session_opened_sensitive_user.py
alerts/ssh_access_signreleng.py
alerts/ssh_lateral.py
alerts/unauth_ssh.py
mq/plugins/mozilla_location.py
mq/plugins/observium.py
mq/plugins/snmptt.py
tests/alerts/test_bruteforce_ssh.py
tests/alerts/test_promisc_kernel.py
tests/alerts/test_session_opened_sensitive_user.py
tests/alerts/test_ssh_access_signreleng.py

details.hostname is a field added due to heka parsing. This is to normalize hostname data fields after decom of heka within our pipeline. The top level mandatory field will be the only field to contain the event source hostname for eventtask events that are parsed. Other hostname fields will be reviewed in a later phase in other data sources.
Many MQ Plugins add the hostname to the details.hostname field. There are also alerts which look for details.hostname to obtain the hostname for an alert. I propose that we add code to look for or validate the top level hostname field, and leave the details.hostname field in the plugin if applicable until we validate that absolutely nothing is using it. Once we can validate that nothing is coming in with details.hostname populated, we can remove that …

hostname field normalization phase I 

---

mq/plugins/auditdFixup.py

in these events, hostname is normally populated as UNKNOWN, while details.dhost is populated with the hostname. This PR corrects this by moving details.dhost into the hostname field.

Fixing details.dhost to be hostname

---

alerts/proxy_drop_non_standard_port.conf
alerts/proxy_drop_non_standard_port.py
tests/alerts/test_proxy_drop_non_standard_port.py

This aims to capture occurances where an attacker is attempting (and failing) to egress via the proxy and making it an alert that IR responders can act on.

Add connect proxy drops to non-std ports alert

---

cloudy_mozdef/Makefile

Revert f0a5db246ee9f9115e81509672176d7efde06867 to get back awscli credential resolution logic which searches through environment variables, and files

Fix makefile s3 upload

---

cloudy_mozdef/cloudformation/base-iam.yml
cloudy_mozdef/cloudformation/mozdef-cloudtrail.yml
cloudy_mozdef/cloudformation/mozdef-parent.yml
cloudy_mozdef/cloudformation/mozdef-sqs.yml

Create an S3 bucket to store CloudTrail logs
Create an SNS Topic to receive notifications of new CloudTrail logs
Create an SQS Topic for inbound event consumption
Create policies to wire everything up
Create CloudTrail
Update the IAM policy to allow MozDef to use these facilities

Add CloudTrail and SQS event consumption support

---

docker/compose/nginx/files/nginx.conf
docker/conf/nginx.conf

nginx, by default, only resolves a proxy_pass one time unless it contains a variable. That means that if meteor, loginput, restapi or kibana are restarted that nginx would have to be restarted as well in order to get the new internal container ip address of the upstream.  Moving all of the proxy_pass upstreams into a variable forces nginx to resolve them.

docker nginx proxy pass fix

---

mq/lib/sqs.py

This should resolve the error
```
Traceback (most recent call last):
File "esworker_cloudtrail.py", line 537, in <module>
main()
File "esworker_cloudtrail.py", line 479, in main
options.secretkey))
TypeError: connect_sqs() got an unexpected keyword argument ‘aws_access_key_id'
```
that was introduced in #867

Change connect_sqs parameter names to match boto

---

cloudy_mozdef/dmake
docker/builder/Dockerfile

In #916 there was a missing `\` character [here](https://github.com/mozilla/MozDef/pull/916#pullrequestreview-170814992).
This PR fixes that and tries to accommodate all AWS environment variables.
I've tried testing this and it looks correct. When I bash into the container
* the environment variables are present
* the mounted files are mounted in the locations that the environment variables point to

Enable dmake to use all AWS environment variables

---

meteor/server/mozdef.js

Previously we generated the token, returned it but didn't store it in the profile which didn't allow the accounts module to validate it. This removes us generating the token since the accounts module is going to do it anyway (and store it).

let accounts module handle the stamped token

---

docs/source/overview.rst

I noticed a typo in the overview while reading about the project.  Trivial change, even for documentation.

Fix typo in overview

---

docker/compose/mozdef_rest/files/index.conf
docker/compose/tester/files/rest_config.conf
docs/source/installation.rst
rest/index.conf

As of https://github.com/mozilla/MozDef/pull/945 this key is no longer used.

Remove references to enableBlockIP config key

---

cloudy_mozdef/Makefile

This will prevent the makefile from passing in a `OIDCClientSecret` value with an empty string

Make cloudy mozdef Makefile catch missing secrets

---

docker/compose/docker-compose-rest.yml
docker/compose/docker-compose-sampledata.yml
examples/demo/sampleevents/events-logins-failure.json
examples/demo/sampleevents/events-logins-success.json
meteor/client/logincounts.js
meteor/server/methods.js
rest/index.conf
rest/index.py
rest/plugins/auth0_logincounts.py
tests/loginput/loginput_index.conf
tests/loginput/loginput_test_suite.py
tests/rest/rest_index.conf
tests/rest/rest_test_suite.py
tests/rest/test_rest_index.py

Update the logincounts function to recent versions of events/endpoints, etc. 
This targets the current auth0 events, instead of the historical ldap events.
Ideally 'authentication' events are generic with category: authentication, details.success as true/false, details.username as the userid in question, etc. 
This PR is a first step in making this count/visualization generic.

Logincounts fix

---

alerts/lib/alerttask.py
tests/alerts/alert_test_suite.py

This bubbles up any exceptions in the unit tests like so
```
../tests/alerts/alert_test_suite.py:151: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <test_proxy_drop_ip.TestAlertProxyDropIP object at 0x10c06b690>, alert_task = <@task: None of None>, test_case = <positive_alert_test_case.PositiveAlertTestCase object at 0x10bd51ed0>
def verify_alert_task(self, alert_task, test_case):
assert alert_task.classname() == self.alert_classname, 'Alert classname did not match expected name'
if test_case.expected_test_result is True:
>           assert len(alert_task.alert_ids) is not 0, 'Alert did not fire as …
```

Modify alert test suite to bubble up exceptions

---

Makefile

This allows a developer to spin up ES and rabbitmq only, so that you can run tests against it locally  (without docker). One still needs to modify the docker-compose-tests.yml file to expose 9200 and 5672, but I think this makes it a little easier to get going.

Add new make target to run only resources for tests

---

docker/compose/tester/Dockerfile

This is to ensure every python file will have pep8 checks ran against it. I also alphabetically ordered the directory names.

Modify tester container to copy all python directories for pep8

---

alerts/guard_duty_probe.py
cloudy_mozdef/cloudformation/mozdef-instance.yml
cloudy_mozdef/cloudformation/mozdef-parent.yml
cloudy_mozdef/packer/packer.json
cron/collectAttackers.py
docker/compose/docker-compose-cloudy-mozdef.yml
docs/source/alert_development_guide.rst
mq/plugins/guardDuty.py
tests/alerts/test_alert_template.template
tests/alerts/test_guard_duty_probe.py

* Make threshold for attackers and cidr blocks configurable.
* Update CloudFormation to configure alert workers
* Add @jeffbryner changes to add guarduty basic alert for port probes
* Set Meteor ROOTURL (Closes #925)
* Add GuardDuty alerts

Add GuardDuty findings collection to AWS MozDef

---

Makefile

This allows folks to run `make run-tests-resources-external` which will run ES and rabbitmq, and have those ports listen externally. This means you no longer have to modify the docker-compose.yml file to say whether or not you want ports exposed.

Add new make target for running test resources externally

---

requirements.txt

This is due to:
CVE-2018-20060
More information
high severity
Vulnerable versions: < 1.23
Patched version: 1.23
urllib3 before version 1.23 does not remove the Authorization HTTP header when following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the Authorization header to be exposed to unintended hosts or transmitted in cleartext.

Update urllib3 version

---

meteor/public/css/dropdowns.css

fix css to allow for IP address without wrapping. Otherwise the pull down is placed on the next line like:

fixup spacing

---

requirements.txt

This currently fixes an issue where configlib v 2.0.2 doesn't version lock everett, so we get similar errors as:
```
Traceback (most recent call last):
File "initial_setup.py", line 12, in <module>
from configlib import getConfig
File "/opt/mozdef/envs/python/lib/python2.7/site-packages/configlib/__init__.py", line 1, in <module>
from configlib import getConfig
File "/opt/mozdef/envs/python/lib/python2.7/site-packages/configlib/configlib.py", line 6, in <module>
from everett.manager import ConfigIniEnv
ImportError: cannot import name ConfigIniEnv
```
Depends on https://github.com/jeffbryner/configlib/pull/8

Update configlib version requirement

---

README.md
cloudy_mozdef/Makefile
cloudy_mozdef/cloudformation/mozdef-parent.yml
docs/source/cloud_deployment.rst

* Update the AWS launch button link
* Use the new public S3 buckets for hosting the CloudFormation templates (mozilla/security#21)
* Create a new make target to publish templates to this bucket

Setup default hosted CloudFormation templates

---

docker/compose/mongodb/Dockerfile
docker/compose/mozdef_syslog/Dockerfile
docker/compose/nginx/Dockerfile

This pins the gpg fingerprint of the yum repositories used both
to prevent the error messages and to make any packages signed by
different keys to cause builds to fail
This is instead of #1038 which had the wrong mongodb key fingerprint

Pin yum repo keys

---

cron/duo_logpull.py

Note: api_version 1 in Duo does not send all events for the authentication logs, forcing us to manually retrieve logs events.
This "fixes it" by using v2

Support api_version 2 for Duo auth logs

---

mq/common.py
mq/esworker_sns_sqs.py
mq/esworker_sqs.py

closes: #970 
Moving the `get_aws_credentials` function to a central `common.py` file and updating worker files to import the new method.

deduplicating get_aws_credentials function

---

Makefile
docker/compose/docker-compose-user-env.yml

This PR adds a make target which calls a copy of the default docker compose file which has an env file enabled for all services. This env file is user supplied via the main makefile.

Add generic env run

---

mq/lib/plugins.py

Since we lowercase all of the event's keys and values, I figured we should be consistent and lowercase the potential matching values from plugins.

Lowercase potential matching keys in mq plugins

---

tests/alerts/alert_test_case.py

In a test I was working on I mistakenly had `events.append(AlertTestSuite.create_events(x,y)`which was appending a single element that itself was a list to my `events` variable. This lead to test errors like
```
@freeze_time("2017-01-01 01:00:00", tz_offset=0)
def test_alert_test_case(self, test_case):
self.verify_starting_values(test_case)
temp_events = test_case.events
for event in temp_events:
temp_event = self.dict_merge(self.generate_default_event(), self.default_event)
merged_event = self.dict_merge(temp_event, event)
>           print merged_event['_source']
E           TypeError: list indices must be integers, not str
../tests/alerts/alert_test_suite.py:152: TypeError
```
This took a lot of time to track down, so I figured a PR to shortcut the debug path was in order.

Assert that there are no nested lists in AlertTestCase events. Much time was spent hunting a bug related to this

---

Makefile

This PR actually sets the variable `ENV_FILE`. It's only a partial solution though as the docker compose call is unaware of the variable. My make knowledge is lacking in finding a solution for that.

Eval to set ENV_FILE

---

alerts/cloudtrail_deadman.py
alerts/deadman.py
alerts/deadman_generic.py
alerts/lib/alerttask.py
alerts/lib/deadman_alerttask.py
alerts/sqs_queues_deadman.py
tests/alerts/test_deadman_generic.py

This speeds up the deadman alert searches quite a bit since we only care if 1 event exists or not.

Create deadman alerttask

---

bot/slack/commands/ip_info.py

I had made https://github.com/mozilla/MozDef/pull/1081 as a temp fix until we updated our release playbook to handle the path correctly. We've since done that, so we should restore the original path structure to the code.

Fixup the geolite db path for slack bot

---

mq/lib/plugins.py

The previous implementations don't fully protect from plugins removing this field.

Project plugins key from mq plugins removing it

---

mozdef_util/mozdef_util/plugin_set.py

This fixes the issue where plugins would stack trace in init() and it would cause the entire worker process to crash.

Add improved error handling to initial parsing of plugin

---

docker/compose/mozdef_meteor/Dockerfile

This reduces the meteor image file from 2.82GB to 2.05GB.

Consolidate docker run lines for meteor container

---

alerts/generic_alert_loader.py
alerts/lib/alerttask.py
docker/compose/mozdef_bootstrap/files/initial_setup.py
mozdef_util/mozdef_util/elasticsearch_client.py
tests/alerts/alert_test_suite.py
tests/mozdef_util/query_models/query_test_suite.py
tests/mozdef_util/query_models/test_aggregation.py
tests/mozdef_util/query_models/test_search_query.py
tests/mozdef_util/test_bulk_queue.py
tests/mozdef_util/test_elasticsearch_client.py
tests/mq/test_esworker_sns_sqs.py
tests/rest/test_rest_index.py
tests/unit_test_suite.py

This fixes the problem where multiple generic alerts could not alert on the same event. Since we are modifying and updating the event (with the alerts that triggered as a result of it), we need to make sure we "refresh" after this action.

Fix duplicate alert generic loader

---

meteor/server/mozdef.js

Reverts mozilla/MozDef#1104 - removing this line prevents restapi from being able to load plugins because it listens on localhost only, thus we are reverting to keep functionality.

Revert "Re-enable node tls reject check in meteor"

---

docker/compose/docker-compose.yml

The syslog container needs to be the last container to run, so even though we're waiting for rabbitmq to start up, we also want to sleep so we ensure we're the last one.

Syslog container wait 30 seconds to boot up

---

mq/plugins/github_webhooks.py

This fixes the deprecation warning message -> https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Fix pyyaml warning messages to use safe loader

---

cloudy_mozdef/cloudformation/mozdef-parent.yml
cloudy_mozdef/cloudformation/mozdef-security-group.yml

This is to satisfy AWS Marketplace requirements to not
default to granting 0.0.0.0/0

Change SSH security group allowed CIDR to user definable

---

mq/esworker_sns_sqs.py
mq/plugins/parse_sshd.py
tests/mq/plugins/test_parse_sshd.py

Strips leading whitespace from summary field.
Parses sshd events based on processname which is built by MQ worker first, as I found that not all events have a details.program. Rather than duplicate fields of the same data, I determined it was better to use the field present across all events.

Resolving issues with sshd events not parsing correctly.

---

docker/compose/docker-compose-cloudy-mozdef.yml

This gets us mozilla-iam/mozilla.oidc.accessproxy#36 which works
around the bug in zmartzone/lua-resty-openidc#249

Pin nginx container to mozillaiam/mozilla.oidc.accessproxy:8334f96

---

cloudy_mozdef/cloudformation/mozdef-cloudtrail.yml

as the ArnEquals Conditions is how to constrain access to the queue, not with Principal
https://docs.aws.amazon.com/sns/latest/dg/sns-sqs-as-subscriber.html#SendMessageToSQS.sqs.permissions
Fixes bug in #1079

Revert part of #1079

---

cloudy_mozdef/packer/packer.json

We found that the increased instance size didn't improve build time significantly

Revert packer instance size change

---

docker/compose/docker-compose-cloudy-mozdef.yml
docker/compose/mozdef_cron/Dockerfile
docker/compose/mozdef_cron/files/cron_entries.txt
docker/compose/mozdef_cron/files/launch_cron

cron jobs don't have access to the docker environment variables.
This, on instance launch, writes the environment to a file and
configured the mozdef crontab to use this on disk environment
This still needs the WORKDIR CMD fix to be added before merging

Make the docker environment variables available to cron jobs

---

docker/compose/docker-compose-cloudy-mozdef.yml

Now that mozilla-iam/mozilla.oidc.accessproxy#36 is merged to master
and built and uploaded to dockerhub as tag `latest` we can go back
to using latest.
Note that in #1155 I updated the nginx container but missed the nginxkibana
container which should have also been pinned to 8334f96 dockerhub tag
resulting in only one of the two mozilla.oidc.accessproxy containers we
use to work correctly

Revert #1155 to latest of mozilla.oidc.accessproxy

---

cloudy_mozdef/Makefile
cloudy_mozdef/ci/deploy
cloudy_mozdef/ci/publish_versioned_templates

* Fix bug where deploy is publishing templates from branches and tags
overwriting the /master branch directory in S3 instead of writing
to their respective branch and tag specific directories
* Add log output and comments to publish_versioned_templates 
* Fix update-dev-stack, removing S3TemplateLocation
* Similar to fc72de6 in #1154

Fix bug where deploy is publishing templates from branches and tags over master

---

Makefile
cloudy_mozdef/ci/deploy
cloudy_mozdef/packer/packer.json

* Add docker-compose pull to packer.json to fetch locally packages other than those we build Fixes #1163 
* Remove CodeBuild call to set-version-and-fetch-docker-container make target
This is because
* We've already built the containers in CodeBuild and don't need to do it again
* We don't need to tag the docker images because `docker-push-tagged` will trigger that
* We don't need to modify docker/compose/docker-compose-cloudy-mozdef.yml because we don't use it in CodeBuild
* Add build make target that mirrors previous behavior
* Previous behavior of build was the build-from-cwd behavior
* Make the sed regex more specific so it only affects MozDef container images

Fix missing packer container fetch and other fixes

---

Makefile
cloudy_mozdef/ci/docker_tag_or_push

* Only tag an image as latest if it came from master branch
* Upload images to dockerhub tagged as latest in addition to those tagged as the branch

Fix docker push and tag

---

cloudy_mozdef/ci/deploy

The tag regex was missing the "v" prefix for the tag name
(e.g. "v1.2.3")
Also removing the march_swarm case as it's no longer needed

Fix deploy so it triggers on tags

---

CHANGELOG
cloudy_mozdef/ci/docker_tag_or_push
docs/source/cicd.rst
docs/source/index.rst

- Docker image tagging for git version tag builds
Previously when tagging a commit, the AWS CodeBuild process would fail with the error
```
Successfully built 57638a88000c
Successfully tagged mozdef/mozdef_alertactions:latest
cloudy_mozdef/ci/docker_tag_or_push tag v1.38.3
"docker tag" requires exactly 2 arguments.
See 'docker tag --help'.
Usage:  docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]
Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE 
```
- Documentation on the CI/CD process

Fix docker tagging and add CI/CD docs

---

.travis.yml

Apr 16, 2019 the default changes from 2.7 to 3.6. This will keep it at 2.7

Define python version for Travis

---

cron/healthToMongo.py

All nodes return the same stats now. We should return all node stats to the about page, and ensure we have visibility into their state too.

Es6 changes eshealth

---

CHANGELOG
Makefile
cloudy_mozdef/ci/deploy
cloudy_mozdef/packer/packer.json
docker/compose/mozdef_meteor/Dockerfile
docs/source/cicd.rst

Changed the CI/CD order to now build docker images in CodeBuild, upload them
to DockerHub and then pull them down in the packer instance. Updated docs.
I confirmed this one works in a branch and built a new stack and updated an existing stack with the resulting artifacts.

Change CI/CD sequence for v1.38.5

---

mq/esworker_cloudtrail.py
mq/esworker_eventtask.py
mq/esworker_papertrail.py
mq/esworker_sns_sqs.py
mq/esworker_sqs.py
mq/plugins/auditdFixup.py
mq/plugins/broFixup.py
mq/plugins/complianceitems.py
mq/plugins/customDocType.py
mq/plugins/dropMessage.py
mq/plugins/googleFixup.py
mq/plugins/ipFixup.py
mq/plugins/netflowFixup.py
mq/plugins/parse_sshd.py
mq/plugins/parse_su.py
mq/plugins/squidFixup.py
mq/plugins/suricataFixup.py
mq/plugins/vidyoCallID.py
mq/plugins/vulnerability.py

Replaces https://github.com/mozilla/MozDef/pull/1130
modified:   mq/esworker_cloudtrail.py
modified:   mq/esworker_eventtask.py
modified:   mq/esworker_papertrail.py
modified:   mq/esworker_sns_sqs.py
modified:   mq/esworker_sqs.py
modified:   mq/plugins/auditdFixup.py
modified:   mq/plugins/broFixup.py
modified:   mq/plugins/complianceitems.py
modified:   mq/plugins/customDocType.py
modified:   mq/plugins/dropMessage.py
modified:   mq/plugins/googleFixup.py
modified:   mq/plugins/ipFixup.py
modified:   mq/plugins/netflowFixup.py
modified:   mq/plugins/parse_sshd.py
modified:   mq/plugins/parse_su.py
modified:   mq/plugins/squidFixup.py
modified:   mq/plugins/suricataFixup.py
modified:   mq/plugins/vidyoCallID.py
modified:   mq/plugins/vulnerability.py
- Removed doc_type (_type) …

Remove doc_type from mq

---

README.md
docs/source/cicd.rst
docs/source/cloud_deployment.rst

The links to mozdef-parent.yml point to the wrong place currently
Also, update documentation link to packer.json

Update docs to point to current release

---

docker/compose/elasticsearch/files/elasticsearch.yml

After 30 days the default trial license expires and generates a warning message at the top of kibana.
To make this not happen, this line will turn on the default basic licensing which will disable the "pay-for" features of kibana.
Feel free to close this PR, as the trial license expires there is an option inside the kibana license management to downgrade to the basic license without having this in the kibana config. I only added this to bring awareness and start dialogue should this be considered a desired configuration.
Features turned off:
https://www.elastic.co/guide/en/x-pack/current/license-expiration.html
- **Watcher**
- **Monitoring**
- **Graph**
- **Reporting**
- **Security**
- **Machine learning**
- **Logstash Pipeline Management**
Once the license expires, calls to the cluster …

adding basic license config, disables pay for features in kibana.

---

docker/compose/mozdef_mq_worker/Dockerfile

This allows us to have multiple .conf files in other deployment processes without having to modify the dockerfile.

Generalize config copy to allow for other worker processes

---

Makefile
cloudy_mozdef/cloudformation/mozdef-instance.yml

This changes from launching docker containers with docker compose
via a make target to a systemd service.
This should ensure graceful shutdown of containers upon instance shutdown.
Previously containers were not shutting down gracefully causing a leftover
lock file for mongodb in the EFS filesystem
Related JIRA ticket [EIS-732](https://jira.mozilla.com/browse/EIS-732)

Use systemd to launch docker containers

---

alerts/celeryconfig.py

My last commit in this vein just made the error apparent. This commit allows for entries to exist in the schedule which are not importable and for the alerts container to carry on without them.

Add case to pass on import errors (after logging)

---

alerts/lib/alerttask.py
cron/syncAlertsToMongo.py
mozdef_util/mozdef_util/query_models/search_query.py
rest/plugins/logincounts.py

Now that ES is more efficient with timestamped data, we can expand the search indices across all events-*, and all alerts-*. Previously, we were restricting our search window between 24 - 48 hours (events to events-previously).
We ran some benchmarks, and it turns out there isn't a very large performance hit when expanding to wildcards:
```
------------ benchmark: 2 tests -----------ons (2/2)
Name (time in ms)            Mean          
-------------------------------------------
test_events_weekly        90.7345 (1.0)    
test_events_wildcard     105.5318 (1.16)   
-------------------------------------------
```

Use wildcard in indices for searching

---

alerts/cloudtrail_logging_disabled.py
tests/alerts/test_cloudtrail_logging_disabled.py

This event logs our query criteria as:
details.eventname: StopLogging
Adding the "details" to the term match should fix this.
Also updated alert unit test.

adding details to eventname so this alert can fire.

---

cloudy_mozdef/cloudformation/mozdef-instance.yml

1. Enable cloudtrail alert
2. Enable watchlist alert with custom config file
3. Disable certain web ui features for cloudy mozdef instance
Depends on https://github.com/mozilla/MozDef/pull/1256

Modify mozdef instance file for cloudy mozdef

---

cloudy_mozdef/cloudformation/mozdef-instance.yml

This line in the user data is referencing a parameter that has been removed.

Remove reference to OIDCDiscoveryURL

---

docker/compose/mozdef_bootstrap/files/dashboards/all_events_area.json
docker/compose/mozdef_bootstrap/files/dashboards/category_pie_graph.json
docker/compose/mozdef_bootstrap/files/dashboards/destinationip_bar_graph.json
docker/compose/mozdef_bootstrap/files/dashboards/sourceip_bar_graph.json

as this breaks kibana due to integer type being passed.
Tested and works fine without specifying versions of dashboards.

removes dashboard version

---

docker/compose/docker-compose.yml

1. This adds a commented out ports line for mongodb container so a developer can easily uncomment to expose locally.
2. Reordered a couple services based on type of container

Add commented out ports line for mongodb

---

cloudy_mozdef/Makefile
cloudy_mozdef/aws_parameters.example.json
cloudy_mozdef/aws_parameters.example.sh
cloudy_mozdef/cloudformation/mozdef-instance.yml
cloudy_mozdef/cloudformation/mozdef-parent.yml
docker/compose/docker-compose-cloudy-mozdef.yml
docker/compose/mozdef_cognito_proxy/Dockerfile
docker/compose/mozdef_cognito_proxy/files/default.conf
docker/compose/mozdef_cognito_proxy/files/htpasswd.example
docs/source/cloud_deployment.rst

https://jira.mozilla.com/browse/EIS-970
> Currently in order to prototype I set the basic auth password for a user to be mozde:mozdef.  Let's randomize this and output it as a parameter that the user can get to in cloudformation console instead.
Currently testing this

Basic auth password should be randomized

---

cloudy_mozdef/cloudformation/mozdef-parent.yml
docker/compose/docker-compose-cloudy-mozdef.yml

This is meant to address https://jira.mozilla.com/browse/EIS-1005
This is a very simple hack to solve this one problem. This is an alternative to the larger solutions proposed in #1303 #1297 so that we can solve this one problem quickly. We still need to come up with a better solution, but just not today.
The notion is that that when these containers come up they'll test for the existence of the Geo IP data file in the docker shared volume. If it's absent the command should fail and the container should stop, then start again (since they're set to `restart: always`. Eventually once the `base` container runs and does the one time fetch, the worker containers should start working
This also clarifies that the `DomainName` parameter is optional. Andrew reports that the basic auth sites work …

Fix geolite db missing issue

---

cloudy_mozdef/Makefile
cloudy_mozdef/cloudformation/mozdef-instance.yml
cloudy_mozdef/cloudformation/mozdef-parent-reinforce.yml
cloudy_mozdef/cloudformation/mozdef-parent.yml
docker/compose/mozdef_cognito_proxy/files/default.conf

Clarify that "unset" isn't a reserved word
Use an empty string as a default to make it easier to understand
Add Rules which validate
* that the user is either choosing basic auth or OIDC but not both.
* that all OIDC parameters are filled out if choosing OIDC.
* that ACM cert is filled out if choosing OIDC
I've tested login to basicauth over http
* basicauth prompt works
* SSL is disabled
I've tested login to OIDC over https
* OIDC prompt works and doesn't ask for basic auth
* SSL works

Replace "unset" with empty string

---

cron/backup.conf
cron/backupSnapshot.py

- Removes non-working restore script generation
- Removes the need to upload the unused script to s3
- Removes the need to store aws creds in code as these will be handled via encrypted keystore now.

Removing restore script functionality as it isn't needed/used

---

cloudy_mozdef/cloudformation/mozdef-cicd-codebuild.yml

Initial capture of the CodeBuild configuration and role in CloudFormation
This likely still requires the one time binding action to link the CodeBuild project with the GitHub project and webhook. But this may get us a large part of the way there before that manual step.

CICD in CloudFormation

---

bot/slack/mozdefbot.py
bot/slack/slack_bot.py

Slack sometimes pushes out updates to their infrastructure, which causes our slackbot to post messages during reconnection. 
This will allow users to turn off this welcome message during reconnection.

Add config option to suppress slack bot welcome message

---

Makefile
docker/compose/elasticsearch/Dockerfile
docker/compose/kibana/Dockerfile
docker/compose/mongodb/Dockerfile
docker/compose/mozdef_alertactions/Dockerfile
docker/compose/mozdef_alerts/Dockerfile
docker/compose/mozdef_base/Dockerfile
docker/compose/mozdef_bootstrap/Dockerfile
docker/compose/mozdef_bot/Dockerfile
docker/compose/mozdef_cognito_proxy/Dockerfile
docker/compose/mozdef_cron/Dockerfile
docker/compose/mozdef_loginput/Dockerfile
docker/compose/mozdef_meteor/Dockerfile
docker/compose/mozdef_mq_worker/Dockerfile
docker/compose/mozdef_rest/Dockerfile
docker/compose/mozdef_sampledata/Dockerfile
docker/compose/mozdef_syslog/Dockerfile
docker/compose/rabbitmq/Dockerfile

* Change pattern of a final recursive chown to instead intentionally setting
the owner and group in the COPY commands. This should avoid a layer that
touches all previously copied files
* Add checks for yum repo signing key fingerprint
* Expand some command line arguments to long form so it's easily
understandably by the reader without having to lookup the man page
* Add removal of yum cache to reduce docker image size
* Change kibana WORKDIR to a fixed and simple value of /kibana
* Cleanup long lines to be more readable
* Use symbolic links instead of internal file copies to reduce docker image size
* Standardize on indents of two spaces

Improve Dockerfiles

---

mozdef_util/setup.py
requirements.txt

virtualenv isn't actually used within MozDef and so isn't needed
tox should only be part of the dev requirements for mozdef_util as it's used in testing, not the setup.py requirements
Fixes #1370

Remove virtualenv requirement from MozDef and tox from mozdef_util

---

cloudy_mozdef/ci/deploy
cloudy_mozdef/cloudformation/mozdef-cicd-codebuild.yml
docs/source/cicd.rst

* Allow setting the CodeBuild project name (as project names can't be changed)
* Fix typo in IAM Policy S3 resource ARN
* Fix IAM Policy CloudWatch log policy statements
* Clarify CodeBuild project description
* Add PrivilegedMode true to fix Docker errors
* Fix GitHub location URL
* Fix FilterGroup for tagged commits
* Update documentation to conform to new AWS CodeBuild provisioning method 
* Add check to prevent CodeBuild rebuilds 
This fixes bugs in #1285

Bugfix AWS CodeBuild settings

---

mq/plugins/cloudtrail.py

This is to prevent details.requestparameters.bucketpolicy.statement.principal.aws being mapped as a url and subsequent service entries being mapped as a keyword causing them to conflict because they were originally only registered as "details.requestparameters.bucketpolicy.statement.principal"

Cloudtrail mapping

---

cron/healthToMongo.py

This fixes the issue of disk usage and total having a bunch of decimal places, we only now include 2.

Update healthToMongo to include 2 digits for disk usage

---

alerts/ldap_password_spray.py

This did not require changes to the tests for this alert, all tests pass.

allows the alert to wrap in UI alerts page.

---

docs/source/alert_development_guide.rst

I think it makes sense to remove this text given that
a) Most alerts will probably be based on specific business logic
and
b) There is a note about including alerts in the mozdef master branch further down

Remove wording around creating a branch for a feature

---

alerts/lib/alert_plugin_set.py

This code was originally put in place when `alert actions` used to be `alert plugins`, and we wanted to know when each and every alert action was triggered. Now, we don't really care when alert plugins receive alerts.

Remove logger entry for alert plugins receiving alerts

---

alerts/ldap_bruteforce.conf
alerts/ldap_bruteforce.py
tests/alerts/test_ldap_bruteforce.py

Makes use of soon to be deployed user attribute to offer per user bruteforce alerting in MozDef.  This should stay as a WIP until we have verifiable data in prod with the exact formats to spec out.

Add LDAP bruteforce alert

---

cloudy_mozdef/lambda_layer/lambdalert.py

This is based on the idea that `cloudy_mozdef/lambda_layer/build/` will get cleaned up in https://github.com/mozilla/MozDef/pull/1464

Fixup flake8 errors in cloudymozdef

---

alerts/proxy_drop_ip.conf
alerts/proxy_drop_ip.py
tests/alerts/test_proxy_drop_ip.py

Adds the capability to white-list certain destinations to prevent alerting when they happen.  In the 169 example, it's a demonstration of a misconfiguration, but not  asecurity issue.  This can be produced in a reporting means for sysadmin tasks, but is not a security event because this IP isn't routable via the proxy.

Add whitelist to proxy drop ip alert

---

mq/plugins/ldap_fixup.py
tests/mq/plugins/test_ldap_fixup.py

I figured it'd be better to not have to disparate fields called the same thing, moving this to details.tls_encrypted is descriptive and should not interfere with any other details.tls field.

moves ldap details.tls to details.tls_encrypted as boolean

---

cron/update_geolite_db.conf
cron/update_geolite_db.py
docker/compose/docker-compose-cloudy-mozdef.yml
docker/compose/docker-compose.yml
docker/compose/mozdef_base/Dockerfile
docker/compose/mozdef_cron/files/cron_entries.txt

This also disables running that script by default, as an account needs to be created beforehand.

Modify update geolocation script to require credentials 

---

Makefile
docker/compose/dev-meteor.yml
docker/compose/mozdef_meteor/Dockerfile

This runs a dev meteor setup in a docker container (with `make run-dev-meteor`), and since we're mounting the local meteor directory, we can modify the files locally and the meteor container will autorefresh with the new file changes.

Allow meteor dev container with refresh on files

---

Makefile
tests/mozdef_util/test_elasticsearch_client.py

This PR includes two changes:
1. An addition to our Makefile to clean docker before running tests and
2. A modification to a test in `test_elasticsearch_client.py` that will guarantee that, if execution of tests occurs across a change from one day to the next, that checks for indices will work as expected and include the new index created.

Fix test index set

---

alerts/geomodel/alert.py
alerts/geomodel_location.py

Note: Before approving and merging the [GeoModel Enrichment](https://github.com/mozilla/MozDef/pull/1595) PR, I would like to have this PR approved and the former adjusted to accommodate these changes.
The problem I am trying to solve here was detected while working on the [GeoModel Enrichment](https://github.com/mozilla/MozDef/pull/1595) PR in which I determined that, to my surprise, hops were only [partially converted to JSON](https://github.com/mozilla/MozDef/pull/1595/commits/24fbfa3227ce3fef1a666ac4e832e285722e279b) in doing
```py
[dict(hop._asdict()) for hop in alert.hops]
```
This is a result of the fact that a `Hop` is itself a `NamedTuple` which contains `Origin` `NamedTuple`s.  Thus, the top-level `Hop` is converted to a `dict` of the form
```py
{
"origin": Origin(...), …
```

Convert Hops to JSON

---

docker/compose/docker-compose-tests.yml

This allows us to run a full docker env of mozdef, in addition to running as many iterations of the test environment at the same time. If we need to run these services on the local docker host, we can run `make run-tests-resources-external`

Comment out mongo external ports for docker test env

---

alerts/geomodel_location.py
tests/alerts/test_geomodel_location.py

This PR modifies the GeoModel alert so that it will set an alert's `details.sourceipaddress` and `details.sourceipv4address` to the IP corresponding to the _last_ hop's destination IP.  I.e. if a user travels from Toronto,CA with IP 1.2.3.4 to San Francisco,US with IP 4.3.2.1, then we will set the source IP addresses to 4.3.2.1 since this is now where the user is acting from.

Fix geomodel sourceipaddress

---

alerts/actions/triage_bot.json
alerts/actions/triage_bot.py
scripts/ingest/insert_elasticsearch.py
tests/alerts/actions/test_triage_bot.py

This PR introduces one main change to the Triage Bot alert action.  Rather than having the action register on _all_ alerts and then programmatically attempt to determine which alert an incoming alert is and then process it based on a few fields, we now instead match strictly on alert `classname`s.  With this addition, we are now able to introduce a configuration option to specify which _supported_ alerts should be enabled or not.

Fix triagebot matching

---

alerts/ldap_add.py
alerts/ldap_delete.py
alerts/ldap_group.py
tests/alerts/test_ldap_add.py
tests/alerts/test_ldap_delete.py
tests/alerts/test_ldap_group.py

Adding negative match for ldap informational events to prevent them from being alerted on.

adding negative match for informational events, and adding unit tests

---

mq/plugins/zoom_fixup.py
tests/mq/plugins/test_zoom_fixup.py

empty values cause parsing errors within MozDef, so we correct for these with this PR.

remove empty start time keys, or assume value

---

cron/duo_logpull.py

- add duo api host to hostname rather than mozdefhostname
- replace UTC logic with toUTC lib
- account for differences between api versions 1 and 2 in normalize function
- Flesh out summaries for administration events.
Did not see any events for telephony in any of the open indices we currently have, so those summaries are not fleshed out.

duo event parsing fixes

---

alerts/plugins/ip_source_enrichment.py

Other alert plugins have lists for their registration.  I found in testing in QA that the alert plugin runs as expected regardless of this change, however I feel that consistency is a good thing.

Make ip_source_enrichment registration consistent

---

alerts/ldap_group.py
mq/plugins/ldap_fixup.py
tests/alerts/test_ldap_group.py
tests/mq/plugins/test_ldap_fixup.py

This PR includes changes to:
1. The `ldap_fixup` MQ plugin that parses out the email address of an LDAP actor and adds its parts to `details.email` and `details.username`.
2. Modifications to the `ldap_group` alert that aggregate on the `details.email` field, including all of the aggregated into the one alert.
I have tested this in QA and verified that it behaves as expected.

Have the ldap_group alert aggregate on details.email

---

alerts/plugins/vpn_assignment.json
alerts/plugins/vpn_assignment.py
tests/alerts/plugins/test_vpn_assignment.py

This PR introduces a new alert plugin, `vpn_assignment`.  This plugin looks at the `sourceipaddress` of any alert and checks to see if it belongs to a VPN.  Upon finding an IP assignment, the plugin will augment the alert with information about the user to whom the IP within the VPN was assigned.  In particular, it creates a new data structure like
```json
"details": {
"vpnassignment": {
"username": "someperson@website.com",
"originalip": "ip.outside.of.vpn",
}
}
```

Create vpn_assignment alert plugin

---

alerts/session_invalidation.py
tests/alerts/test_session_invalidation.py

When the session invalidation application logs a message indicating that a user A has terminated sessions for user B, this alert fires with information about those users and their sessions.  In this case, there are duplicates because I ran my test a couple times with the same target user.

Alert when the Session Invalidation application is used to terminate a user's sessions

---

meteor/package-lock.json
meteor/package.json

Revert "Bump jquery from 3.4.0 to 3.5.0 in /meteor"

---

cron/auth02mozdef.py

This will both change the Auth0 raw field to be called raw_value
and will change the representation from a Python repr to a JSON
encoded string. This will allow ElasticSearch to index this value
and make it searchable.
This is similar to what was done in #1586 and support #1607

Change Auth0 raw field from str repr to json

---

rest/index.py
tests/rest/test_rest_index.py

When the triage bot updates an alert's status to "acknowledged" in response to a user indicating that an alert was expected via Slack, we previously only updated the new "status" field.  This PR introduces a small change that results in the triage bot MQ plugin that reads user responses adding the "acknowledged" and "acknowledgedby" fields to the alert in MongoDB so that it will show up as "ack'd" in the MozDef UI.

Set an alert to acknowledged when the triage bot updates its status

---

alerts/triagebot_escalation.conf
alerts/triagebot_escalation.py
mq/plugins/triage_bot.py
tests/alerts/test_triagebot_escalation.py
tests/mq/plugins/test_triage_bot.py

- Adds a summary to the triagebot events that get sent when a user responds to a slack prompt.
- Adds an alert that will trigger a Pagerduty event in the event a user responds to the negative.
- Adds unit testing for this alert to ensure it functions as intended
- Setting the severity to INFO until we monitor it in production and decide it's good to set to CRITICAL

adding new triagebot escalation alert

---

mozdef_util/HISTORY.rst
mozdef_util/Makefile
mozdef_util/README.rst
mozdef_util/requirements_dev.txt
mozdef_util/setup.py
requirements.txt
tests/alerts/actions/test_triage_bot.py
tests/mozdef_util/utilities/test_dict2List.py

To remove the leftover plugins: artifact we must update the mozdef_util pypi package.
This PR is to ensure that update gets captured and also allows for review of the update.

Deprecate old plugins field

---

alerts/auth0_vertical_password_guessing.conf
alerts/auth0_vertical_password_guessing.py
tests/alerts/test_auth0_vertical_password_guessing.py

This alert is designed to detect a style of attack where an attacker attempts a 1-<less than lockout or bruteforce threshold> per user across multiple users.  This is generally considered a vertical password guessing or password spraying behavior.

Auth0 vertical password guessing alert

---

docs/source/geomodel/specifications/v0_1.rst

There is a small typo in docs/source/geomodel/specifications/v0_1.rst.
Should read `somewhere` rather than `somehwere`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, somehwere -> somewhere

---

Makefile

Allows for things like:
```
make restart SERVICES=alerts
make restart SERVICES="alerts alertactions"
```
Useful for restarting only specific services during development. It build them and their dependencies, and restart those that changed.

Add the Makefile 'restart' recipe
