- mq/plugins/vulnerability.py
Add a vulnerability processing plugin to MozDef
> add MozDef vulnerability processing plugin

- examples/heka-lua-bro/bro_intel.lua
I've discovered today they were switched.
> Correct the order of "where" and "category" fields

- meteor/app/client/incidents.js
- meteor/app/client/investigations.js
- meteor/app/client/ipcif.js
- meteor/app/client/ipdshield.js
- meteor/app/client/ipintel.js
- meteor/app/client/ipwhois.js
Fixed deprecation warnings where ever I could find them.
> Fixed deprecation warnings for meteor with Template.name.helper

- mq/plugins/rra.py
This is necessary to support the latest RRAs
> Support validation for new data classification

- mq/plugins/rra.py
This enhance the validation accuracy ;-)
In particular this let rra2json submit rra 2.4.3 and 2.4.4 formats
> Support more validation filters to accomodate different RRA fields.

- meteor/app/client/attackers.html
- meteor/app/client/attackers.js
- meteor/app/client/mozdef.js
Some UI changes have been made to accomodate the IP filter in the `sidenav` Here is the screenshot of the same:
> Attackers: Added filter to allow search by IP, fix for #292

- docs/source/installation.rst
Currently a Work in Progress. We will be appending to this PR.
> New documentation for installation

- alerts/squiderrors_pyes.py
Matches on DENIED string from squid ("1091084609.110 351 10.49.4.0 TCP_DENIED/407 2112 GET http://www.mozilla.org/ -
NONE/- text/html ") for ex.
> Initial support for squid alerts coming from EC2

- rest/index.py
> Added REST API endpoint to create an Incident. Fix for #268.

- docs/source/installation.rst
I was reading issue #325 , so I thought of adding some final touches to the installation documentation. @jeffbryner I also noticed that the previous doc update (about Landmass VR) was also not updated in readthedocs. Maybe you have to reconfigure the hook for readthedocs or something.
> Documentation fix for installation

- bot/mozdefbot.py
> Various fixes to mozdefbot

- meteor/app/client/investigationAdd.html
Corrected Case of Investigation Summary Field
> Corrected  Case in investigationAdd.html

- mq/plugins/rra.py
Add support for RRA versionning
> Sync with rra2json message format

- alerts/bro_notice_dashboard.json
- cron/collectAttackers.py
- examples/demo/sampleevents/alertcreating-bro-notice.json
- examples/es-docs/bro_notice.json
> Update bro_notice category to bronotice

- alerts/bro_intel_dashboard.json
- alerts/bro_intel_pyes.py
- cron/broAlerts.py
- examples/demo/sampleevents/alertcreating-bro-intel.json
- examples/es-docs/bro_intel.json
- examples/heka-lua-bro/bro_known_certs.lua
- examples/heka-lua-bro/bro_socks.lua
> Standardize other bro_* categories

- mq/plugins/fluentdSqsFixup.py
> corrected typo in mq/plugins/fluentdSqsFixup.py

- alerts/supervisord.alerts.conf
- initscripts/mozdefalerts
corrected mozdefalerts init script to avoid race conditions with other supervisord processes, also adding supervisord.alerts.conf to repo.
> Corrected mozdefalerts init script and added supervisord.alerts.conf

- lib/slapd2mozdef.py
> Update slapd importer with local timezone

- alerts/uwsgi-alertplugins.ini
- docs/source/code.rst
- initscripts/mozdefalertplugins
added new init script and ini for mozdef alert plugins created by @mpurzynski
> alert plugins changes

- cron/auth02mozdef.json
- cron/auth02mozdef.py
This add support for our auth0 POC
> Add support to import auth0 logs into mozdef

- config/mongod.conf
- systemdfiles/\
- systemdfiles/kibana.service
- systemdfiles/mongod.service
New Branch for systemd files and configurations.
Two new directories:
* configs
* systemdfiles
The configs dir contains a mongod.conf
the systemdfiles contains a mongod and kibana4 unit file.
> Convert2systemd

- mq/plugins/geoip.py
> Update GeoLiteCity.dat location in mq plugin

- cron/defaultMappingTemplate.json
updating mapping to be more aligned with what you see in ES (order of objects)
Having it mirror what's in ES makes it easier to diff if something goes crazy
> Re-org of default dynamic template

- docker/Dockerfile
- docker/compose/mozdef_meteor/Dockerfile
Fixup both meteor docker files to allow bcrypt to build.
> Docker fixups for bcrypt build

- rest/plugins/cymon.py
This reverts commit cae96f73b12442ad3bf2215acf69d7767bdadc3f.
> Revert "Remove cymon rest plugin"

- meteor/app/client/mozdef.js
To help with #398 set a default useful filter.
> set a default veris filter

- meteor/app/client/verisTags.html
Also to assist with #398, add a tooltip instructing what to do to add a tag, to the list of tags.
> Add tooltip for #398

- lib/plugin_set.py
- tests/lib/test_plugin_set.py
- tests/lib/test_plugins/plugin1.py
- tests/lib/test_plugins/plugin2.py
- tests/lib/test_plugins/plugin3.py
- tests/lib/test_plugins/plugin4.py
- tests/lib/test_plugins/plugin5.py
- tests/lib/test_plugins/plugin6.py
- tests/lib/test_plugins/plugin7.py
- tests/lib/test_plugins/plugin8.py
This PR creates a plugin set class, that will be used in the areas of mozdef that load plugins (alertplugins, mq).
> Add plugin set class to lib

- docker/compose/mozdef_loginput/files/index.conf
- docker/compose/mozdef_rest/files/index.conf
- loginput/index.conf
- loginput/index.py
- rest/index.conf
- rest/index.py
I originally modified rest and loginput to listen externally, but figured a config option would be best here.
> Add config option for rest and loginput for listening host address

- alerts/generic_alert_loader.py
Fixes https://github.com/mozilla/MozDef/issues/512
> Fix example json of generic alert

- docker/compose/nginx/files/nginx.conf
> Correct Nginx proxy redirect in docker compose nginx config.

- mq/plugins/filterlog.py
- tests/mq/plugins/test_filterlog.py
This allows us to parse filterlog type firewall message. For example, those coming from pfSense.
> Add filterlog firewall mq plugin

- alerts/cloudtrail_logging_disabled.py
- mq/esworker_cloudtrail.py
- tests/alerts/test_cloudtrail_deadman.py
- tests/alerts/test_cloudtrail_logging_disabled.py
- tests/mq/test_esworker_cloudtrail.py
This modifies the cloudtrail worker to:
1. Saves all other fields that aren't used for required fields from the event, in 'details'
2. Enables plugins to run
> Improve cloudtrail worker

- meteor/.meteor/packages
- meteor/app/client/incidentAdd.html
- meteor/app/client/incidentEdit.html
- meteor/app/client/incidents.js
- meteor/app/client/investigationAdd.html
- meteor/app/client/investigationEdit.html
- meteor/app/client/investigations.js
- meteor/app/client/mozdefhealth.html
- meteor/app/client/mozdefhealth.js
- meteor/public/css/bootstrap.css
- meteor/public/css/mozdef.css
- Updated field cases to be consistent
- Updated fields that were missing colons for consistency
- Updated input areas with more descriptive text
- Added tooltips to some areas for more descriptive information about what is expected.
> Meteor tooltip updates

- README.md
> [Docs] - Mozilla/MozDef - README.md - changing markdown layout

- config/defaultMappingTemplate.json
- lib/elasticsearch_client.py
- lib/utilities/is_cef.py
- lib/utilities/logger.py
- lib/utilities/remove_at.py
- lib/utilities/to_unicode.py
- mq/esworker_cloudtrail.py
- mq/esworker_eventtask.py
- mq/esworker_papertrail.py
- mq/esworker_sns_sqs.py
- mq/esworker_sqs.py
- mq/lib/plugins.py
- mq/plugins/complianceitems.py
- mq/plugins/ipFixup.py
- mq/plugins/vulnerability.py
This was branched originally from https://github.com/mozilla/MozDef/pull/588  so that PR should get reviewed/merged first.
> Redo cloudtrail improvements

- meteor/app/client/mozdef.js
This reverts commit 37f169f86a83bf2a1332534b3c99932c89183a2e.
> Revert "Add XHR patch to handle external auth correctly"

- requirements.txt
This reverts commit f300276e042fbd9a3c34b282707e6b2b374e4c82, reversing
changes made to 26ceb0db486f640757acd9a4d96a1821ff9fa1ce.
> Revert "Merge pull request #612 from mozilla/pip_pkg_updates"

- cron/collectAttackers.py
- cron/collectSSHFingerprints.py
- cron/correlateUserMacAddress.py
- cron/eventStats.py
- cron/healthAndStatus.py
- cron/healthToMongo.py
- cron/import_threat_exchange.py
- cron/okta2mozdef.py
- cron/syncAlertsToMongo.py
- cron/verify_event_fields.py
Replaces https://github.com/mozilla/MozDef/pull/602 since we're separating ES5 from ES6 changes
> Modify cron scripts to remove _type field

- alerts/feedback_events.json
- alerts/feedback_events.py
- docker/compose/docker-compose.yml
- docker/compose/mozdef_bootstrap/Dockerfile
- docker/compose/mozdef_cron/files/backup.conf
- docker/conf/initial_setup.py
- docker/conf/supervisor.conf
- mq/esworker_sns_sqs.py
- mq/plugins/alert_information.py
- tests/alerts/test_feedback_events.py
- tests/mq/plugins/test_alert_information.py
- tests/mq/test_esworker_sns_sqs.py
- tests/unit_test_suite.py
Depends on https://github.com/mozilla/MozDef/pull/658
> Fixup worker and alert for sso feedback events

- alerts/write_audit.conf
- alerts/write_audit.py
- tests/alerts/test_write_audit.py
This is a conversion of the write_audit.json into a custom alert.
Will remove this alert from generic alerts once merged and pushed.
> Write audit custom

- alerts/trace_audit.conf
- alerts/trace_audit.py
- tests/alerts/test_trace_audit.py
One alert for all instances of ptrace/strace events regardless of category aggregated by executing user.
> Consolidated ptrace/strace events into custom alert

- meteor/app/client/mozdef.js
Failed to set session var before use, fixing bug.
> Fix unset bug

- meteor/app/client/globe.html
fix up some old code/formatting/styles.
> Globefixin

- meteor/app/client/layout.js
use the menu item target instead of the document.body to avoid unwanted scrolling on .focus()
> use the menu item instead of body

- lib/utilities/dot_dict.py
- mq/plugins/guardDuty.py
- tests/lib/utilities/test_dot_dict.py
Plug in and updates to docdict class to allow for easier fixup of guard duty messages. This fixes dates to be isoformat and pulls IP addresses from some common locations
> Guard duty plugin

- rest/index.py
update to match current pymongo cursor handling
> fix the cursor

- mq/plugins/guardDuty.py
As per: https://github.com/mozilla/guardDuty2MozDef/pull/1/files
> rename details.service to details.finding

- alerts/honeycomb.py
- tests/alerts/test_honeycomb_case.py
First attempt in creating a MozDef alert.
> Add alert for honeycomb

- alerts/proxy_drop_executable.py
- alerts/proxy_drop_non_standard_port.py
- tests/alerts/test_proxy_drop_executable.py
- tests/alerts/test_proxy_drop_non_standard_port.py
Just a minor tweak to summary name
> Standardize some proxy drop summary verbiage

- .travis.yml
- Makefile
- docs/source/installation.rst
> clean up test targets

- cloudy_mozdef/cloudformation/mozdef-amazonmq.yaml
A wild CFN template appears. 
This is template is for AmazonMQ.
> Initial commit for AmazonMQ CFN

- cloudy_mozdef/cloudformation/mozdef-instance.yml
- cloudy_mozdef/cloudformation/mozdef-parent.yml
Set default AMI ID to the actual AMI
> Add parent CloudFormation stack

- cloudy_mozdef/cloudformation/mozdef-amazonmq.yaml
And fix some dumb formatting mistakes!
> Derive the AMQ Broker name from the StackName

- cloudy_mozdef/cloudformation/mozdef-instance.yml
- cloudy_mozdef/cloudformation/mozdef-parent.yml
- cloudy_mozdef/cloudformation/mozdef-security-group.yml
Fix default subnet ids
Fix AMI
> Move security group to it's own stack

- cloudy_mozdef/cloudformation/mozdef-efs.yml
Worked on the EFS CFN template with @Phrozyn and made some changes to get it working.
> Made changes to the EFS CFN template

- cloudy_mozdef/cloudformation/mozdef-parent.yml
Also added OIDC attributes for later consumption.
> Added EFS to the parent stack template. 

- cloudy_mozdef/cloudformation/mozdef-parent.yml
How else will it get the parameters????
> Exposing IDP Parameters to the MozDefInstance

- cloudy_mozdef/cloudformation/mozdef-instance.yml
Change TargetGroupARNs to fix bug
Add UpdatePolicy
Set healthcheck
> Fix bug in stack update failing

- cloudy_mozdef/Makefile
- cloudy_mozdef/cloudformation/base-iam.yml
- cloudy_mozdef/cloudformation/mozdef-cloudtrail.yml
- cloudy_mozdef/cloudformation/mozdef-efs.yml
- cloudy_mozdef/cloudformation/mozdef-es.yml
- cloudy_mozdef/cloudformation/mozdef-instance.yml
- cloudy_mozdef/cloudformation/mozdef-mq.yml
- cloudy_mozdef/cloudformation/mozdef-parent.yml
- cloudy_mozdef/cloudformation/mozdef-security-group.yml
- cloudy_mozdef/cloudformation/mozdef-sqs.yml
Remove all unnecessary quoting
Swap in single quotes where quoting is required or useful for clarity
Exclude cfn-lint check with bug
Resolve outstanding cfn-lint warnings
> Clean CloudFormation YAML and fix cfn-lint warnings

- docker/compose/docker-compose-cloudy-mozdef.yml
This should use the new environment file created in #866
> Add mq_cloudtrail docker service

- cloudy_mozdef/cloudformation/mozdef-instance.yml
How that infosec_workweek is merged to master we should pull from master
> Change instance user-data git pull to master

- docs/source/installation.rst
> Documentation Correction: Formatting, Typo Fixes, and Version updates

- docs/source/alert_development_guide.rst
- docs/source/demo.rst
- docs/source/index.rst
- docs/source/overview.rst
There's a ton of tribal knowledge about developing alerts that isn't well documented in a public place.  here's a start to do that. I will need a few iterations to get going.
> Alert Development Guide

- cloudy_mozdef/cloudformation/mozdef-instance.yml
> Add Kibana URL environment variable for Meteor

- alerts/proxy_drop_exfil_domains.conf
- alerts/proxy_drop_exfil_domains.py
- tests/alerts/test_proxy_drop_exfil_domains.py
> Create an alert on attempts to use known exfil domains

- docs/source/demo.rst
Add some bits about the memory and file system requirements for the docker-compose build environment.
> Update docker requirements closes #949

- docker/compose/mozdef_rest/files/index.conf
- docker/compose/tester/files/rest_config.conf
- meteor/client/alertdetails.js
- meteor/client/alertssummary.html
- meteor/imports/settings.js
This fixes the URL to alert details in kibana
> Remove hash from kibanaurl

- meteor/client/menu.html
- meteor/client/menu.js
Fixes #904 
Is supported by #954
> allow for relative kibanaURL

- docs/source/index.rst
- docs/source/usage.rst
Added a one liner to send a very basic test event.
> Doc update simple test, closes #952

- tests/alerts/test_alert_template.template
> Fix incorrect notify mozdefbot field in template

- cron/auth02mozdef.py
Fix up field that doesn't always exist.
> user_id doesn't always exist

- docs/source/alert_development_guide.rst
I wrote this guide after working through my first alert and thought it might be helpful to others.
> Add initial alert guide

- cron/duo_logpull.py
use the setter in the mozdef_client object we are using, rather than set a dict key
> update category set

- cron/auth02mozdef.py
msg.category doesn't actually set the category.. switch to set_category instead.
> match mozdef_client's expectation for set_category

- alerts/bruteforce_ssh.py
Catch log entries like: Failed keyboard-interactive/pam for root
> Catch keyboard-interactive

- docker/compose/mozdef_bootstrap/files/initial_setup.py
Addresses https://github.com/mozilla/MozDef/issues/1041
> Improve logic to determine if index_patterns are created on setup

- docs/source/alert_development_guide.rst
This comes from knowledge acquired from the exchange on 
https://github.com/mozilla/MozDef/issues/1034
It's information I will doubtless forget and hopefully it will be useful to others as well.
> Add discussion of the aggreg object

- docs/source/alert_development_guide.rst
Minor update to comment on log ordering (or lack there of).
> Add comment about log ordering

- cloudy_mozdef/Makefile
- cloudy_mozdef/cloudformation/mozdef-instance.yml
- cloudy_mozdef/cloudformation/mozdef-security-group.yml
- docs/source/cloud_deployment.rst
* Add details to MozDef for AWS documentation 
* Separate dev and prod makefile targets
>  Redirect all HTTP calls to HTTPS URLs 

- cron/duo_logpull.py
This *should* fix the duplicates. Needs a bit of testing.
See also https://community.duo.com/t/duo-admin-api-admin-v2-logs-authentication/3836/11
NOTE: I used black for formatting hence the formatting changes :| On the flip side this make our formatting proper ;-)
I added inline comments to the PR so that you can see exactly what changed and why
> Fix API calls to use next_offset as this is the newer way to paginate Note: only authentication logs support this

- bot/slack/slack_bot.py
Matches up with https://github.com/mozilla/MozDef/blob/master/meteor/public/css/mozdef.css#L163
> Update severity colors to match web ui colors

- docker/compose/mozdef_base/Dockerfile
- docker/compose/mozdef_cron/Dockerfile
- docker/compose/mozdef_meteor/Dockerfile
Implements https://github.com/mozilla/MozDef/issues/911
> Remove cache after yum install commands in docker files

- cloudy_mozdef/cloudformation/mozdef-parent.yml
This is a requirement for admission to the AWS Marketplace
> Change AMI parameter to static region map of AMI IDs

- cloudy_mozdef/cloudformation/mozdef-instance.yml
> Fix variable collision between AWS CloudFormation Fn::Sub and bash

- cloudy_mozdef/aws_parameters.example.json
- cloudy_mozdef/cloudformation/mozdef-instance.yml
* Update example parameters to match new parent parameter list
* Fix missing path to rabbitmq env file
* Fix incorrect env file name
> Fix instance provisioning and examples

- cloudy_mozdef/Makefile
- cloudy_mozdef/cloudformation/mozdef-instance.yml
- cloudy_mozdef/packer/packer.json
* Fix Rabbit MQ password variable escaping
* Increase disk size as MozDef is 11GB (larger than 8GB)
* Fix create-dev-stack, removing S3TemplateLocation
* Increase packer builder instance size to speed up builds
> Fixes and build improvements

- cloudy_mozdef/ci/deploy
> Move hub-login

- mozdef_util/mozdef_util/plugin_set.py
- tests/alerts/alert_test_suite.py
- tests/unit_test_suite.py
This will require building a new version of mozdef_util, and I will do that once we do the initial review.
> Fix plugins directory

- Makefile
- cloudy_mozdef/buildspec.yml
This reverts my efforts to fix #1163 where I tried improving the
sed line that modifies the compose file
* #1165
* #1168
I opened issue #1169 to explore solving this further
Also this does
*  Remove wget progress output during CodeBuild build
> Revert attempts to improve sed command

- cloudy_mozdef/packer/packer.json
> Fix missing env files for pull and grow packer build volume

- docker/compose/docker-compose-cloudy-mozdef.yml
- docker/compose/docker-compose.yml
- docker/compose/kibana/Dockerfile
- docker/compose/mozdef_bootstrap/files/initial_setup.py
- mozdef_util/mozdef_util/elasticsearch_client.py
Instead this calls the kibana API and sets the defaultIndex
Fixes #1174
> Remove need to hard code kibana version in bootstrap

- alerts/lib/alerttask.py
Replaces https://github.com/mozilla/MozDef/pull/1129
> Remove doc_type from alerts

- docker/compose/mozdef_bootstrap/files/dashboards/sample_dashboard.json
Removes hardcoded hits and version from sample_dashboard in docker mozdef_bootstrap.
Fixes #1208
> Fixes dashboard error on docker spinup.

- cron/auth02mozdef.py
see code comments for more info
note that this has been Black formatted, the only code change is in a separate commit:
https://github.com/mozilla/MozDef/pull/1215/commits/cfe1fe401c8f45413ac38ba841dc4a0cdccbca80
> fix paging when fetching auth0 logs

- .flake8
- cron/correlateUserMacAddress.py
- cron/healthToMongo.py
- cron/syncAlertsToMongo.py
This shores up the flake8 failures.
> Fix pep8 doctype removal

- cloudy_mozdef/buildspec.yml
- cloudy_mozdef/ci/deploy
Also add some additional logging
> Avoid installing packer in CodeBuild unless we're going to build

- docs/source/installation.rst
This fixes a warning when trying to build the docs.
> Fix installation doc warning

- cron/collectAttackers.py
> Fix bruteforcer search

- alerts/get_watchlist.py
- cron/backupSnapshot.py
- cron/google2mozdef.py
- cron/pruneIndexes.py
- cron/rotateIndexes.py
Didn't touch the logging stuff left in bot:
- roulette.py
- zilla.py
- mozdefbot.py
Wasn't sure if those were left using logging for a reason. Will check with @pwnbus
> Removing old logger configuration for mozdef_util logger import.

- CODEOWNERS
> Add support for CODEOWNERS

- meteor/.meteor/packages
- meteor/.meteor/versions
- meteor/client/alertssummary.html
- meteor/client/alertsummary.js
- meteor/client/fqdnBlocklistTable.html
- meteor/client/fqdnBlocklistTable.js
- meteor/client/incidentTable.html
- meteor/client/incidents.js
- meteor/client/investigationEdit.html
- meteor/client/investigationTable.html
- meteor/client/investigations.js
- meteor/client/ipBlocklistTable.html
- meteor/client/ipBlocklistTable.js
- meteor/client/mozdef.js
- meteor/client/preferences.html
- meteor/client/preferences.js
- meteor/client/watchlistTable.html
- meteor/client/watchlistTable.js
- meteor/imports/collections.js
- meteor/imports/helpers.js
- meteor/imports/models.js
- meteor/imports/themes/classic/mozdef.css
- meteor/imports/themes/dark/mozdef.css
- meteor/imports/themes/light/mozdef.css
- meteor/server/mozdef.js
An update to the UI to use the paginations component https://github.com/Kurounin/Pagination and to allow the user to set their desired page size.
> Paginations

- cloudy_mozdef/cloudformation/mozdef-es.yml
- cloudy_mozdef/cloudformation/mozdef-instance.yml
> Multiple Fixes

- README.md
Opinions/criticism/Suggestions welcome.
> Adding Logo to Readme

- cloudy_mozdef/ci/deploy
- cloudy_mozdef/experiments/alert-writer.yml
* Add alert writers environment so people can play with alerts.
* Still needs to be added to parent stack.
https://jira.mozilla.com/browse/EIS-975
> Package the alert writers environment as cloudformation

- meteor/imports/themes/classic/mozdef.css
- meteor/imports/themes/dark/mozdef.css
- meteor/imports/themes/side_nav_dark/mozdef.css
> Improving modal window text color, and button text color.

- cloudy_mozdef/Makefile
- cloudy_mozdef/cloudformation/mozdef-instance.yml
- cloudy_mozdef/cloudformation/mozdef-parent-reinforce.yml
- cloudy_mozdef/cloudformation/mozdef-parent.yml
- docker/compose/mozdef_cognito_proxy/Dockerfile
Fixes for https://jira.mozilla.com/browse/EIS-970
> fixes EIS-970

- cloudy_mozdef/Makefile
- docker/compose/mozdef_cognito_proxy/Dockerfile
@gene1wood just as FYI as it might be useful (see commit msg)
> fix stack update and noecho params

- alerts/deadman_generic.py
- alerts/lib/alerttask.py
- cron/syncAlertsToMongo.py
- mozdef_util/mozdef_util/query_models/search_query.py
- rest/plugins/logincounts.py
- tests/unit_test_suite.py
As well as override that value in generic deadman.
> Revert event indices wildcard

- loginput/index.py
This PR adds a bulk message decode route compatible with rsyslog's jsonarray output. In my testing all that was required was to decode the raw message which was nice. Discussion on the subject started here
https://github.com/mozilla/MozDef/issues/1246
I'm not sure what the `# don't post the items telling us where to post things..` part was about so I just copied over the publishing logic.
Edit: Rsyslog docs for http batch formats
https://www.rsyslog.com/doc/v8-stable/configuration/modules/omhttp.html#batch-format
> Add json array input decode with try catch to fall back to string splitting

- cron/defaultMappingTemplate.json
- mq/plugins/geoip.py
This allows us to use the map visualization like:
> Add geo_points for sourceip and destinationip

- README.md
> issue fix - typo fix in README.MD

- cron/createIPBlockList.py
- cron/sqs_queue_status.py
- cron/update_ip_list.py
> Swap out boto3 for boto in a few cron scripts

- benchmarking/workers/json2Mozdef.py
A brush stroke to conform to pep8, at least putting on one style page.
> json2Mozdef.py - removed style inconsistency

- meteor/client/incidentAdd.html
and remove trailing quote
Fixes #1307
> Clarify summary placeholder text

- cron/closeIndices.py
- cron/esCacheMaint.py
- mozdef_util/HISTORY.rst
- mozdef_util/mozdef_util/elasticsearch_client.py
- mozdef_util/setup.py
- requirements.txt
- tests/mozdef_util/test_elasticsearch_client.py
This also creates mozdef_util version 3.0.3.
> Implement separate function for getting open indices

- alerts/lib/alerttask.py
- cron/auth02mozdef.py
- rest/index.py
- rest/plugins/cymon.py
- rest/plugins/fqdnblocklist.py
- rest/plugins/ipblocklist.py
- rest/plugins/logincounts.py
- rest/plugins/vpc_blackhole.py
- rest/plugins/watchlist.py
This also fixes the dict_values error received in rest plugins.
> Move away from sys.std and use logger

- README.md
- docs/source/alert_development_guide.rst
- docs/source/benchmarking.rst
- docs/source/cicd.rst
- docs/source/cloud_deployment.rst
- docs/source/overview.rst
- docs/source/usage.rst
This more closely conforms to [how best to punctuate bullet lists][1].
Thanks to @Siddharth1698 for noticing these inconsistencies and suggesting
a fix in #1400
[1]: https://www.businesswritingblog.com/business_writing/2012/01/punctuating-bullet-points-.html
> Fix documentation bullet list syntax

- meteor/imports/themes/dark/mozdef.css
- meteor/imports/themes/side_nav_dark/mozdef.css
in dark theme and dark side nav, the font color var names were different, this led to inconsistent colorization in modal views and other areas as only one var name will subsist from the default theme, where only the value of that var name is the only thing that will change from theme to theme.
> Updates css font var to standardize across all dark themes

- docs/source/usage.rst
Quick little PR adding a reference to the rsyslog module. I can also add some example config if you guys like, but let me know where I should stick that.
> Add reference to rsyslog and omhttp module

- meteor/imports/themes/classic/mozdef.css
- meteor/imports/themes/dark/mozdef.css
- meteor/imports/themes/light/mozdef.css
- meteor/imports/themes/side_nav_dark/mozdef.css
This should be tested on QA first
> adding bottom margin to make pagination visible before footer

- meteor/imports/themes/classic/mozdef.css
- meteor/imports/themes/dark/mozdef.css
- meteor/imports/themes/light/mozdef.css
- meteor/imports/themes/side_nav_dark/mozdef.css
Adjusts bottom padding for ring charts and pagination container, removes container margin-bottom
> css tweaks for positioning of key elements

- alerts/actions/dashboard_geomodel.py
- alerts/actions/pagerDutyTriggerEvent.py
- alerts/lib/alerttask.py
- bot/irc/mozdefbot.py
- bot/slack/mozdefbot.py
- tests/alerts/actions/test_dashboard_geomodel.py
- tests/alerts/alert_test_suite.py
Reverts mozilla/MozDef#1528
This is causing unexpected errors throughout the alert pipeline to slack
> Revert "Alert action invoke"

- meteor/client/alertssummary.html
- meteor/client/alertsummary.js
- meteor/client/mozdef.js
I also removed the alerts record limit, since it wasn't actually working correctly, and I feel is no longer needed due to pagination.
> Fixup alerts page to set 1 day as default time limit

- meteor/client/alertssummary.html
- meteor/client/alertsummary.js
- meteor/imports/collections.js
- corrects indentation
- wraps status in td tags
- removes quotes from status in js files
> triage_bot_patch

- alerts/geomodel/locality.py
- alerts/geomodel_location.py
Really quick PR to address an issue that was bugging me.  I got rid of the magic strings from the geomodel code and replaced them with some constructor methods that place them instead.
> Replace magic strings with constructor methods

- mq/plugins/cloudtrail.py
- tests/mq/plugins/test_cloudtrail.py
This changes raw_value to JSON so it's searchable in ES. Changes logic from #685
> Change raw_value to JSON

- alerts/geomodel_location.py
- tests/alerts/test_geomodel_location.py
> Revert "Fix geomodel sourceipaddress"

- alerts/geomodel_location.py
- tests/alerts/test_geomodel_location.py
Blocked by https://github.com/mozilla/MozDef/pull/1614
> Reapply sourceipaddress fix to geomodel

- cron/defaultMappingTemplate.json
pre-emptively adding this for a future discussion.
> disabling date detection to improve on mapping conflicts

- meteor/package-lock.json
> Revert "backporting package-lock from production"

- mq/plugins/remove_dots.py
- tests/mq/plugins/test_remove_dots.py
eis-2202 removes dots from beginning and/or end of a key name
> remove dots from the start or end of a key

- alerts/auth0_bruteforce_user.conf
- alerts/auth0_bruteforce_user.py
- tests/alerts/test_auth0_bruteforce_user.py
This alert provides the ability to detect and alert on brute-force attacks against a single Auth0 user.
> Auth0 username/password bruteforce alert

- requirements.txt
Fix #1698
The issue is due to the recent release of the v2.0.0 of PyJWT (https://pypi.org/project/PyJWT/#history)
Freezing PyJWT to the previous release (v1.7.1) solves the issue.
> Freeze PyJWT

- .flake8
- rest/index.py
Give endpoint methods unique names so that they can be imported by other modules.
> Give endpoint methods unique names
